import type {
  DatasetPreview,
  LabelPreview,
  PromptPreview,
  ReportDetail,
  RunDetail,
  RunsResponse,
  StepDetail,
} from "@/types/api";

export const runsFixture: RunsResponse = {
  runs: [
    {
      run_id: "run_alpha",
      workflow_name: "demo_wf",
      workflow_hash: "wh_abc123",
      workflow_spec_hash: "wsh_abc123",
      status: "completed",
      started_at: "2026-04-14T12:00:00Z",
      finished_at: "2026-04-14T12:05:00Z",
      parent_run_id: null,
      error: null,
      step_counts: { total: 3, completed: 2, failed: 0, running: 0, reused: 1, pending: 0, other: 0 },
      has_report: true,
    },
    {
      run_id: "run_beta",
      workflow_name: "demo_wf",
      workflow_hash: "wh_abc123",
      workflow_spec_hash: "wsh_abc123",
      status: "failed",
      started_at: "2026-04-13T12:00:00Z",
      finished_at: "2026-04-13T12:03:00Z",
      parent_run_id: null,
      error: "step `probe` failed: out of memory",
      step_counts: { total: 3, completed: 1, failed: 1, running: 0, reused: 0, pending: 1, other: 0 },
      has_report: false,
    },
  ],
};

export const runDetailFixture: RunDetail = {
  run: runsFixture.runs[0],
  workflow_payload: { kind: "workflow", name: "demo_wf", steps: [] },
  nodes: [
    {
      id: "cap",
      step_name: "cap",
      runner: "capture",
      spec_kind: "capture",
      family: "capture",
      status: "completed",
      artifact_id: "a_cap",
      artifact_kind: "capture",
      reused: false,
      runtime_app_id: null,
    },
    {
      id: "probe",
      step_name: "probe",
      runner: "analysis",
      spec_kind: "probe",
      family: "readout",
      status: "completed",
      artifact_id: "a_probe",
      artifact_kind: "probe",
      reused: true,
      runtime_app_id: null,
    },
    {
      id: "report",
      step_name: "report",
      runner: "report",
      spec_kind: "report",
      family: "report",
      status: "completed",
      artifact_id: "a_report",
      artifact_kind: "report",
      reused: false,
      runtime_app_id: null,
    },
  ],
  edges: [
    { source: "cap", target: "probe", kind: "declared" },
    { source: "probe", target: "report", kind: "resolved" },
  ],
  steps: [
    {
      step_name: "cap",
      step_index: 0,
      runner: "capture",
      status: "completed",
      spec_kind: "capture",
      family: "capture",
      artifact_id: "a_cap",
      artifact_kind: "capture",
      started_at: "2026-04-14T12:00:00Z",
      finished_at: "2026-04-14T12:02:00Z",
      runtime_app_id: null,
      reused_from_run_id: null,
      reused_from_artifact_id: null,
      step_semantic_hash: "s_cap",
      step_spec_hash: "p_cap",
      depends_on: [],
      resolved_depends_on: [],
    },
    {
      step_name: "probe",
      step_index: 1,
      runner: "analysis",
      status: "completed",
      spec_kind: "probe",
      family: "readout",
      artifact_id: "a_probe",
      artifact_kind: "probe",
      started_at: "2026-04-14T12:02:00Z",
      finished_at: "2026-04-14T12:03:00Z",
      runtime_app_id: null,
      reused_from_run_id: "run_prior",
      reused_from_artifact_id: "a_probe_prior",
      step_semantic_hash: "s_probe",
      step_spec_hash: "p_probe",
      depends_on: ["cap"],
      resolved_depends_on: ["cap"],
    },
    {
      step_name: "report",
      step_index: 2,
      runner: "report",
      status: "completed",
      spec_kind: "report",
      family: "report",
      artifact_id: "a_report",
      artifact_kind: "report",
      started_at: "2026-04-14T12:03:00Z",
      finished_at: "2026-04-14T12:05:00Z",
      runtime_app_id: null,
      reused_from_run_id: null,
      reused_from_artifact_id: null,
      step_semantic_hash: "s_report",
      step_spec_hash: "p_report",
      depends_on: ["probe"],
      resolved_depends_on: ["probe"],
    },
  ],
};

export const stepDetailFixture: StepDetail = {
  step: runDetailFixture.steps[1],
  spec: { kind: "probe" },
  spec_summary: [{ label: "kind", value: "probe" }],
  upstream: [
    {
      step_name: "cap",
      runner: "capture",
      artifact_id: "a_cap",
      artifact_kind: "capture",
      status: "completed",
    },
  ],
  downstream: [
    {
      step_name: "report",
      runner: "report",
      artifact_id: "a_report",
      artifact_kind: "report",
      status: "completed",
    },
  ],
  artifact: null,
  result_summary: null,
  report_artifact_id: "a_report",
  has_prompt: true,
  has_dataset: true,
  has_labels: true,
  has_artifact: false,
  has_results: true,
};

export const datasetPreviewFixture: DatasetPreview = {
  available: true,
  source: {
    kind: "memory",
    env_var: null,
    table: null,
    query: null,
    limit: null,
    identity: null,
  },
  rows: [
    {
      example_key: "ex0",
      case_key: null,
      prompt_preview: "Prompt number 0",
      labels: { class: "pos" },
      metadata: {},
    },
    {
      example_key: "ex1",
      case_key: null,
      prompt_preview: "Prompt number 1",
      labels: { class: "neg" },
      metadata: {},
    },
  ],
  total_rows: 8,
  sample_size: 2,
  dataset_options: null,
  resolved_from_step: null,
};

export const labelPreviewFixture: LabelPreview = {
  available: true,
  labels: [
    {
      label_name: "class",
      unique_values: 2,
      buckets: [
        { value: "pos", count: 4, fraction: 0.5 },
        { value: "neg", count: 4, fraction: 0.5 },
      ],
      numeric_summary: null,
      source_step: "cap",
    },
  ],
  samples: [],
  resolved_from_step: null,
};

export const promptPreviewWithSectionFixture: PromptPreview = {
  available: true,
  degraded: false,
  examples: [
    {
      example_key: "ex0",
      text: "System: you are helpful\nUser: STRATEGY: go left\nAssistant: ok",
      sections: [
        {
          id: "STRATEGY",
          label: "STRATEGY",
          char_start: 31,
          char_end: 45,
          token_start: 8,
          token_end: 11,
          selected: true,
          pooling: null,
        },
      ],
      selection: {
        section_label: "STRATEGY",
        token_start: 8,
        token_end: 11,
        char_start: 31,
        char_end: 45,
        pooling: "mean",
        exact_tokens: true,
        sentence: "section STRATEGY -> tokens 8..11 -> mean pooled",
      },
      tokenizer: "gpt2",
      warnings: [],
    },
  ],
};

export const promptPreviewDegradedFixture: PromptPreview = {
  available: true,
  degraded: true,
  degraded_reason: "tokenizer unavailable — showing char-span fallback",
  examples: [
    {
      example_key: "ex0",
      text: "System: you are helpful\nUser: STRATEGY: go left\nAssistant: ok",
      sections: [
        {
          id: "STRATEGY",
          label: "STRATEGY",
          char_start: 31,
          char_end: 45,
          token_start: null,
          token_end: null,
          selected: true,
          pooling: null,
        },
      ],
      selection: {
        section_label: "STRATEGY",
        token_start: null,
        token_end: null,
        char_start: 31,
        char_end: 45,
        pooling: "mean",
        exact_tokens: false,
        sentence: "section STRATEGY -> chars 31..45 -> mean pooled (section-level, not exact tokens)",
      },
      tokenizer: null,
      warnings: ["tokenizer unavailable — showing char-span fallback"],
    },
  ],
};

export const reportDetailFixture: ReportDetail = {
  artifact_id: "a_report",
  artifact_kind: "report",
  run_id: "run_alpha",
  report: { template: "summary" },
  summary: null,
  headline: { probe: { acc: 0.8 } },
  figures: [
    {
      figure_id: "probe/main",
      path: "assets/probe.png",
      step_name: "probe",
      result_kind: "probe_result",
      chart_kind: "bar",
      title: "Probe accuracy",
      caption: "accuracy per class",
      primary: true,
    },
  ],
  tables: [
    {
      slug: "probe",
      step_name: "probe",
      result_kind: "probe_result",
      rows: 2,
      columns: ["metric", "value"],
      path: "tables/probe.json",
    },
  ],
  results: [
    { name: "probe_results.json", path: "results/probe_results.json", step_name: "probe", bytes: 1024 },
  ],
  unsupported_inputs: [],
};
