// Generated by hand from pipelines_v2/dashboard/models.py. Kept in lockstep.
// When adding fields to the backend models, update this file.

export type StepStatus =
  | "completed"
  | "failed"
  | "running"
  | "reused"
  | "pending"
  | "blocked"
  | string;

export type StepFamily =
  | "capture"
  | "derive"
  | "readout"
  | "representation"
  | "mechinterp"
  | "report"
  | string;

export interface StepCounts {
  total: number;
  completed: number;
  failed: number;
  running: number;
  reused: number;
  pending: number;
  other: number;
}

export interface RunSummary {
  run_id: string;
  workflow_name: string | null;
  workflow_hash: string;
  workflow_spec_hash: string;
  status: string;
  started_at: string;
  finished_at: string | null;
  parent_run_id: string | null;
  error: string | null;
  step_counts: StepCounts;
  has_report: boolean;
  report_local: boolean | null;
}

export interface RunsResponse {
  runs: RunSummary[];
}

export interface StepSummary {
  step_name: string;
  step_index: number;
  runner: string;
  status: StepStatus;
  spec_kind: string | null;
  family: StepFamily | null;
  artifact_id: string | null;
  artifact_kind: string | null;
  started_at: string | null;
  finished_at: string | null;
  runtime_app_id: string | null;
  reused_from_run_id: string | null;
  reused_from_artifact_id: string | null;
  step_semantic_hash: string | null;
  step_spec_hash: string | null;
  depends_on: string[];
  resolved_depends_on: string[];
}

export interface DagNode {
  id: string;
  step_name: string;
  runner: string;
  spec_kind: string | null;
  family: StepFamily | null;
  status: StepStatus;
  artifact_id: string | null;
  artifact_kind: string | null;
  reused: boolean;
  runtime_app_id: string | null;
}

export interface DagEdge {
  source: string;
  target: string;
  kind: "declared" | "resolved";
}

export interface RunDetail {
  run: RunSummary;
  workflow_payload: Record<string, unknown>;
  nodes: DagNode[];
  edges: DagEdge[];
  steps: StepSummary[];
  report: RunReportStatus | null;
}

export interface RunReportStatus {
  has_report_step: boolean;
  step_name: string | null;
  artifact_id: string | null;
  local_available: boolean;
  reason: string | null;
}

// Phase C — step detail
export interface ResolvedDep {
  step_name: string;
  runner?: string | null;
  artifact_id?: string | null;
  artifact_kind?: string | null;
  status?: string | null;
}

export interface ArtifactSummary {
  artifact_id: string;
  artifact_kind: string;
  schema_version: number;
  created_at: string;
  operation_spec_hash: string;
  operation_semantic_hash: string;
  storage_refs: Record<string, unknown>;
  metadata: Record<string, unknown>;
  input_artifact_refs: string[];
  runner: Record<string, unknown>;
  engine: Record<string, unknown>;
  example_coverage: Record<string, unknown>;
}

export interface ResultSummary {
  headline: Record<string, unknown> | null;
  tables: Array<{ name: string; rows: number; columns: string[] }>;
  raw_available: boolean;
}

export interface StepDetail {
  step: StepSummary;
  spec: Record<string, unknown>;
  spec_summary: Array<{ label: string; value: string }>;
  upstream: ResolvedDep[];
  downstream: ResolvedDep[];
  artifact: ArtifactSummary | null;
  result_summary: ResultSummary | null;
  report_artifact_id: string | null;
  has_prompt: boolean;
  has_dataset: boolean;
  has_labels: boolean;
  has_artifact: boolean;
  has_results: boolean;
}

export interface StepDetailListResponse {
  step_details: StepDetail[];
}

// Phase D — dataset / labels
export interface DatasetPreviewRow {
  example_key: string;
  case_key: string | null;
  prompt_preview: string;
  labels: Record<string, unknown>;
  metadata: Record<string, unknown>;
}

export interface DatasetSourceInfo {
  kind: string;
  env_var?: string | null;
  table?: string | null;
  query?: string | null;
  limit?: number | null;
  identity?: Record<string, unknown> | null;
  name?: string | null;
  dataset_id?: string | null;
  deferred?: boolean;
  total_examples?: number | null;
  prompt_column?: string | null;
  example_key_column?: string | null;
  label_columns?: string[];
  case_columns?: string[];
  metadata_columns?: string[];
  selection_keys?: string[] | null;
  construction?: Array<{ label: string; value: string }>;
}

export interface DatasetPreview {
  available: boolean;
  reason?: string | null;
  source?: DatasetSourceInfo | null;
  rows: DatasetPreviewRow[];
  total_rows?: number | null;
  sample_size?: number | null;
  dataset_options?: Array<{ step_name: string; label: string }> | null;
  resolved_from_step?: string | null;
}

export interface LabelDistributionBucket {
  value: string;
  count: number;
  fraction: number;
}

export interface LabelDistribution {
  label_name: string;
  unique_values: number;
  buckets: LabelDistributionBucket[];
  numeric_summary?: {
    min: number;
    max: number;
    mean: number;
    stddev: number;
  } | null;
  source_step?: string | null;
}

export interface LabelPreview {
  available: boolean;
  reason?: string | null;
  labels: LabelDistribution[];
  samples: Array<{
    example_key: string;
    prompt_preview: string;
    labels: Record<string, unknown>;
  }>;
  resolved_from_step?: string | null;
}

// Phase E — prompt preview
export interface PromptSection {
  id: string;
  label: string;
  char_start: number;
  char_end: number;
  token_start: number | null;
  token_end: number | null;
  selected: boolean;
  pooling: string | null;
}

export interface PromptSelection {
  section_label: string | null;
  token_start: number | null;
  token_end: number | null;
  char_start: number | null;
  char_end: number | null;
  pooling: string | null;
  exact_tokens: boolean;
  sentence: string;
}

export interface PromptExample {
  example_key: string;
  text: string;
  sections: PromptSection[];
  selection: PromptSelection | null;
  tokenizer: string | null;
  warnings: string[];
}

export interface PromptPreview {
  available: boolean;
  reason?: string | null;
  degraded: boolean;
  degraded_reason?: string | null;
  examples: PromptExample[];
}

export interface ResultPreviewTable {
  name: string;
  rows: Array<Record<string, unknown>>;
  columns?: string[];
  total_rows?: number | null;
  truncated?: boolean;
}

export interface ResultPreview {
  available: boolean;
  reason?: string | null;
  path?: string | null;
  bytes?: number | null;
  payload?: Record<string, unknown> | null;
  headline?: Record<string, unknown> | null;
  tables?: ResultPreviewTable[];
  truncated?: boolean;
  truncation_reason?: string | null;
}

// Phase F — reports
export interface ReportFigure {
  figure_id: string;
  path: string;
  step_name: string | null;
  result_kind: string | null;
  chart_kind: string | null;
  title: string | null;
  caption: string | null;
  primary: boolean;
}

export interface ReportTableSummary {
  slug: string;
  step_name: string | null;
  result_kind: string | null;
  rows: number;
  columns: string[];
  path: string;
}

export interface ReportResult {
  name: string;
  path: string;
  step_name: string | null;
  bytes: number;
}

export interface ReportDetail {
  artifact_id: string;
  artifact_kind: string;
  run_id: string | null;
  report: Record<string, unknown> | null;
  summary: Record<string, unknown> | null;
  headline: Record<string, unknown> | null;
  figures: ReportFigure[];
  tables: ReportTableSummary[];
  results: ReportResult[];
  unsupported_inputs: Array<Record<string, unknown>>;
}

export interface ReportGenerationResponse {
  run_id: string;
  step_name: string;
  artifact_id: string;
  report: ReportDetail;
}

// Phase G — project / experiment report index
export interface ProjectLabelExplanation {
  name: string;
  description: string | null;
  source: string | null;
}

export interface ProjectDataSource {
  name: string | null;
  dataset_id: string | null;
  description: string | null;
  source: string | null;
  example_count: number | null;
  label_names: string[];
}

export interface ProjectReportSummary {
  report_key: string;
  report_id: string;
  title: string;
  path: string;
  relative_path: string;
  artifact_id: string | null;
  run_id: string | null;
  generated_at: string | null;
  summary_text: string | null;
  headline: Record<string, unknown> | null;
  data_sources: ProjectDataSource[];
  labels: ProjectLabelExplanation[];
  workflow_names: string[];
  result_kinds: string[];
  figure_count: number;
  table_count: number;
  result_count: number;
}

export interface ProjectExperimentSummary {
  experiment_id: string;
  title: string;
  experiment_category: string;
  path: string;
  relative_path: string;
  summary_text: string | null;
  workflow_names: string[];
  spec_paths: string[];
  data_sources: ProjectDataSource[];
  labels: ProjectLabelExplanation[];
  reports: ProjectReportSummary[];
}

export interface ProjectPhaseSummary {
  phase_id: string;
  title: string;
  path: string;
  relative_path: string;
  phase_doc_path: string | null;
  summary_text: string | null;
  experiments: ProjectExperimentSummary[];
}

export interface ProjectSummary {
  project_id: string;
  title: string;
  path: string;
  relative_path: string;
  status: string | null;
  primary_question: string | null;
  thin_waist: string | null;
  description: string | null;
  core_labels: string[];
  candidate_datasets: string[];
  phases: ProjectPhaseSummary[];
}

export interface ProjectsResponse {
  project_roots: string[];
  projects: ProjectSummary[];
}
