"""Generic activation patch surface."""

from pipelines.interp.patching.activation_patch_core import (
    ALLOWED_PATCH_MODES as ALLOWED_ACTIVATION_PATCH_MODES,
    ActivationPatchSpec,
    PATCH_MODE_ADD_DIRECTION,
    PATCH_MODE_PROJECT_OUT,
    PATCH_MODE_RANDOM_CONTROL,
    PATCH_MODE_SWAP_COMPONENTS,
    PATCH_MODE_SWAP_MEAN,
    clear_batch_patch_specs,
    clear_patch_spec,
    collect_patch_stats,
    harvest_batch_tensor_stats,
    init_activation_patching,
    install_qwen3_moe_activation_patch_hooks,
    register_patch_basis,
    set_batch_patch_specs,
    set_patch_spec,
    teardown_activation_patching,
)

__all__ = [
    "ActivationPatchSpec",
    "ALLOWED_ACTIVATION_PATCH_MODES",
    "PATCH_MODE_ADD_DIRECTION",
    "PATCH_MODE_PROJECT_OUT",
    "PATCH_MODE_RANDOM_CONTROL",
    "PATCH_MODE_SWAP_COMPONENTS",
    "PATCH_MODE_SWAP_MEAN",
    "clear_batch_patch_specs",
    "clear_patch_spec",
    "collect_patch_stats",
    "harvest_batch_tensor_stats",
    "init_activation_patching",
    "install_qwen3_moe_activation_patch_hooks",
    "register_patch_basis",
    "set_batch_patch_specs",
    "set_patch_spec",
    "teardown_activation_patching",
]
